version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-container
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: arielhalevy
      POSTGRES_PASSWORD: Ariel67788
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: users-sdk-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/usersdb
      SPRING_DATASOURCE_USERNAME: arielhalevy
      SPRING_DATASOURCE_PASSWORD: Ariel67788
    depends_on:
      - postgres

volumes:
  postgres_data:

